# Generated by Django 6.0.1 on 2026-01-26 19:21

from django.db import migrations, models


# Initial schema for the directory app.
class Migration(migrations.Migration):

    # Marks this as the first migration in the app.
    initial = True

    # No dependencies for the initial schema.
    dependencies = [
    ]

    # Create the Business model with core fields.
    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
