# Generated by Django 6.0.1 on 2026-01-26 20:05

from django.db import migrations, models


# Add slug field for friendly URLs on businesses.
class Migration(migrations.Migration):

    # Depends on the initial Business model.
    dependencies = [
        ('directory', '0001_initial'),
    ]

    # Add the slug field to Business.
    operations = [
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
