# Generated by Django 6.0.1 on 2026-01-26 20:25

from django.db import migrations, models


# Add hero and logo image fields to businesses.
class Migration(migrations.Migration):

    # Requires the slug migration.
    dependencies = [
        ('directory', '0002_business_slug'),
    ]

    # Add image upload fields.
    operations = [
        migrations.AddField(
            model_name='business',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_hero/'),
        ),
        migrations.AddField(
            model_name='business',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/'),
        ),
    ]
