# Generated by Django 6.0.1 on 2026-02-01 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


# Add the Review model for business ratings and comments.
class Migration(migrations.Migration):

    # Requires the image fields on Business.
    dependencies = [
        ("directory", "0003_business_images"),
    ]

    # Create the Review table and its relation to Business.
    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("comment", models.TextField(max_length=1000)),
                ("is_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="directory.business",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
