# Generated by Django 6.0.1 on 2026-02-01 00:00

from django.db import migrations, models


# Add Google Place ID field for external review lookups.
class Migration(migrations.Migration):

    # Requires the Review model migration.
    dependencies = [
        ("directory", "0004_review"),
    ]

    # Add the google_place_id field to Business.
    operations = [
        migrations.AddField(
            model_name="business",
            name="google_place_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
