# Generated by Django 6.0.1 on 2026-02-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="google_place_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
