# Generated by Django 6.0.1 on 2026-02-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0005_business_google_place_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="deal_text",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]